build:
  dependencies:
    before: ~
    override:
      - "cp .env.scrutinizer .env"
      - "composer global require hirak/prestissimo"
      - "composer install --no-interaction --prefer-source --no-scripts --ignore-platform-reqs"
  environment:
    mysql: 5.7
  nodes:
    analysis:
      tests:
        override:
          command:
            - php-scrutinizer-run
            - "vendor/bin/phpunit --coverage-clover=coverage"
          coverage:
            file: coverage
            format: clover
checks:
  php:
    code_rating: true
    fix_doc_comments: true
    fix_identation_4spaces: true
    fix_line_ending: true
    fix_linefeed: true
    fix_php_opening_tag: true
    fix_use_statements:
      order_alphabetically: true
      preserve_blanklines: true
      preserve_multiple: false
      remove_unused: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
filter:
  dependency_paths:
    - vendor/*
  excluded_paths:
    - libs/*
    - resources/*
    - storage/*
    - resources/views/themes/*
    - public/plugins/*
    - public/assets/*
    - database/*
    - config/*
    - bootstrap/*
    - docs/*
    - tests/*
tools:
  php_analyzer: true
  php_code_sniffer:
    config:
      standard: PSR2
  php_cs_fixer: true
  sensiolabs_security_checker: true
