build:
    dependencies:
        # Overwrites inferred commands
        override:
          - composer install --prefer-source

        before:
          - cp .env.scrutinizer .env
    environment:
        redis: true
        mysql: 5.7
        php:
            version: '7.2.0'
            ini:
                memory_limit:     "1024M"
    tests:
        before:
              - chmod -R 777 storage/
              - chmod -R 777 bootstrap/cache
        override:
              -
                command: 'vendor/bin/phpunit --coverage-clover=coverage_file'
                coverage:
                  file: 'coverage_file'
                  format: 'clover'
              - command: 'php-scrutinizer-run'
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
          remove_unused: true
          preserve_multiple: false
          preserve_blanklines: true
          order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

filter:
    excluded_paths:
      - "vendor/*"
      - "libs/*"
      - "resources/*"
      - "storage/*"
      - "public/themes/*"
      - "public/plugins/*"
      - "database/*"
      - "config/*"
      - "bootstrap/*"
      - "docs/*"
      - "tests/*"
tools:
    sensiolabs_security_checker: true
    php_analyzer: true
    php_cs_fixer: true
    php_code_sniffer:
      config:
        standard: PSR2
