build:
    dependencies:
        # Overwrites inferred commands
        override:
          - 'composer install --no-interaction --prefer-source --no-scripts --ignore-platform-reqs'
        before:
          - cp .env.scrutinizer .env
          - mysql -u root -e "SET GLOBAL innodb_file_per_table = 1;"
          - mysql -u root -e "SET GLOBAL innodb_file_format = 'BARRACUDA';"
          - mysql -u root -e "SET GLOBAL innodb_large_prefix = 1;"
          - mysql -u root -e "CREATE DATABASE TEST;"
          - mysql -u root -e "GRANT ALL ON TEST.* TO 'TEST'@'localhost' IDENTIFIED BY 'TEST';"
          - mysql -u root -e "GRANT FILE ON *.* TO 'TEST'@'localhost';"
          - mysql -u TEST -pTEST TEST < resources/db/schema/mysql-ddl.sql
          - php artisan migrate
          - php artisan db:seed
    environment:
        memcached: true
        mysql: 5.6
        php:
            version: '7.1.6'
            ini:
                memory_limit:     "4096M"
    tests:
       override: [php-scrutinizer-run]
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
          remove_unused: true
          preserve_multiple: false
          preserve_blanklines: true
          order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

filter:
    excluded_paths:
      - "vendor/"
      - "libs/"
      - "resources/"
      - "storage/"
      - "public/themes/"
      - "public/plugins/"
      - "database/"
      - "config/"
      - "bootstrap/"
      - "docs/"
      - "tests/"
tools:
    sensiolabs_security_checker: true
    php_analyzer: true
    php_code_sniffer:
      config:
        standard: PSR2
