preset: laravel

risky: false
alpha_ordered_imports: true

disabled:
    - no_tab_indentation
    - unused_use

finder:
    exclude:
      - "tests"
      - "storage"
      - "vendor"
      - "docs"
      - "public"
      - "resources"
      - "bootstrap"
      - "database/migrations"
      - "database/seeds"
      - "database/fixtures"