preset: laravel

risky: false

disabled:
    - no_tab_indentation
    - unused_use

finder:
    exclude:
      - "tests"
      - "storage"
      - "vendor"
      - "docs"
      - "public"
      - "resources"
      - "bootstrap"
      - "database/migrations"
      - "database/seeds"
      - "database/fixtures"

js:
  finder:
    not-name:
      - webpack.mix.js
css: true